### ISSUE TITLE
Reunitem.io

### ISSUE THREAD

**Issue by grstreten** [jacobwalkr/caerus-web#3]
Ok, so this is probably the wrong place to post, but hey..
I see that reunitem.io is still live; is Dan still hosting it via DigitalOcean?

I have no means to view the changes that have happened, and I don't know whats happening as far as the hosting - is there a script that can be set up so that we can see whats going on, via the site?

I thought I read a little while back in an email that reunitem.io was being cancelled, but I don't know..

If somebody who knows could put this out there, then that'd be cool :)

Cheers,
George

**Comment by ghost** [comment]
The email addresses were being cancelled, not the hosting

**Comment by grstreten** [comment]
But can a script of some sort be set up so that every so often the source will be cloned to the server?

**Comment by grstreten** [comment]
Sorry, misworded a little bit.. Can we set up a script that will every so often (for example every hour) clone the Git Repo to Dan's server, replacing whats already there? This would then ensure that we can pretty much constantly see the latest code in action..

**Comment by grstreten** [comment]
Cool, just wanted to know - it didn't look like anything had changed.. It would still be cool if we could though, so that if anybody makes a change, then it can go straight up without faffing about
